export const GETUSERS = "GETUSERS";
export const GETQUESTIONS = "GETQUESTIONS";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SAVEANSWERTOQUESTIONS = "SAVEANSWERTOQUESTIONS";
export const SAVEANSWERTOUSERS = "SAVEANSWERTOUSERS";
